name: Java CI with Gradle

on:
  push:
    branches: [ main, 2nd-Branch ]
  pull_request:
    branches: [ main, 2nd-Branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run tests
        run: ./gradlew test

      - name: Install Infer
        run: |
          VERSION=1.1.0; \
          curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" \
          | sudo tar -C /opt -xJ && \
          echo "/opt/infer-linux64-v$VERSION/bin" >> $GITHUB_PATH

      - name: Run Infer
        run: infer run -- ./gradlew build

      - name: Upload Infer results
        uses: actions/upload-artifact@v3
        with:
          name: infer-out
          path: infer-out